In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [105]:
df = pd.read_csv('Football_teams_price_data.csv')
df.head(5)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   
2         30.443897                    43                     3   
3         28.177194                    84                    19   
4         20.652317                    36                    36   

   MatchesDrawnLastSeason  MatchesLostLastSeason  \
0                      36                     20   
1                      35                     31   
2                       9                     28   
3                      19                     34   
4                      10                      9   

   TotalGoalsConcededLastSeason  TotalRevenueLastSeason  StadiumCapacity  \
0                            51              337.552001            55766   
1                            84              264.850402            15307   
2                            72              363.423205            77050   
3                            22              296.719959            61440   
4                            80              480.928532            78563   

   AverageAttendance  TransferSpendingLastSeason  ...  Country    Manager  \
0         5229.74272                  177.592126  ...  England  Manager B   
1        46172.73888                  125.441952  ...    Spain  Manager C   
2        78334.25499                   43.776137  ...    Spain  Manager C   
3        60080.42382                  183.936395  ...    Italy  Manager C   
4        10940.95051                   14.881518  ...   France  Manager D   

   TeamFormation    PlayingStyle  HomeCity   StadiumType MainSponsor  \
0        4-2-3-1  Counter-Attack    City C  Multipurpose   Sponsor B   
1       3/4/2003       Defensive    City C  Multipurpose   Sponsor A   
2       3/5/2002       Attacking    City D       Classic   Sponsor A   
3       4/3/2003  Counter-Attack    City C       Classic   Sponsor D   
4        4-2-3-1  Counter-Attack    City D    Historical   Sponsor C   

  KitManufacturer OwnershipType          Price  
0  Manufacturer B       Private     43,751,816  
1  Manufacturer B    Consortium    859,750,388  
2  Manufacturer C    Consortium  2,168,913,729  
3  Manufacturer B    Consortium  1,426,481,894  
4  Manufacturer B    Consortium  4,038,110,631  

[5 rows x 26 columns]

In [106]:
df.shape

(50000, 26)

In [107]:
df.columns

Index(['AveragePlayerAge', 'TotalGoalsLastSeason', 'MatchesWonLastSeason',
       'MatchesDrawnLastSeason', 'MatchesLostLastSeason',
       'TotalGoalsConcededLastSeason', 'TotalRevenueLastSeason',
       'StadiumCapacity', 'AverageAttendance', 'TransferSpendingLastSeason',
       'TransferIncomeLastSeason', 'NumberOfTrophies', 'MarketValueOfSquad',
       'AveragePlayerMarketValue', 'YouthAcademyRating', 'League', 'Country',
       'Manager', 'TeamFormation', 'PlayingStyle', 'HomeCity', 'StadiumType',
       'MainSponsor', 'KitManufacturer', 'OwnershipType', 'Price'],
      dtype='object')

In [108]:
df1 = df.drop('StadiumCapacity',axis = 'columns')
df1.head(5)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   
2         30.443897                    43                     3   
3         28.177194                    84                    19   
4         20.652317                    36                    36   

   MatchesDrawnLastSeason  MatchesLostLastSeason  \
0                      36                     20   
1                      35                     31   
2                       9                     28   
3                      19                     34   
4                      10                      9   

   TotalGoalsConcededLastSeason  TotalRevenueLastSeason  AverageAttendance  \
0                            51              337.552001         5229.74272   
1                            84              264.850402        46172.73888   
2                            72              363.423205        78334.25499   
3                            22              296.719959        60080.42382   
4                            80              480.928532        10940.95051   

   TransferSpendingLastSeason  TransferIncomeLastSeason  ...  Country  \
0                  177.592126                 79.972750  ...  England   
1                  125.441952                  7.679349  ...    Spain   
2                   43.776137                136.648762  ...    Spain   
3                  183.936395                168.683160  ...    Italy   
4                   14.881518                188.768072  ...   France   

     Manager  TeamFormation    PlayingStyle HomeCity   StadiumType  \
0  Manager B        4-2-3-1  Counter-Attack   City C  Multipurpose   
1  Manager C       3/4/2003       Defensive   City C  Multipurpose   
2  Manager C       3/5/2002       Attacking   City D       Classic   
3  Manager C       4/3/2003  Counter-Attack   City C       Classic   
4  Manager D        4-2-3-1  Counter-Attack   City D    Historical   

  MainSponsor KitManufacturer OwnershipType          Price  
0   Sponsor B  Manufacturer B       Private     43,751,816  
1   Sponsor A  Manufacturer B    Consortium    859,750,388  
2   Sponsor A  Manufacturer C    Consortium  2,168,913,729  
3   Sponsor D  Manufacturer B    Consortium  1,426,481,894  
4   Sponsor C  Manufacturer B    Consortium  4,038,110,631  

[5 rows x 25 columns]

In [109]:
df1 = df1.drop('AverageAttendance',axis='columns')

In [110]:
df1 = df1.drop('TransferSpendingLastSeason',axis='columns')

In [111]:

df1 = df1.drop('YouthAcademyRating',axis='columns')

In [112]:
df1 =df1.drop('League',axis='columns')
df1 =df1.drop('Manager',axis='columns')
df1 =df1.drop('TeamFormation',axis='columns')
df1 =df1.drop('HomeCity',axis='columns')
df1 =df1.drop('StadiumType',axis='columns')
df1 =df1.drop('MainSponsor',axis='columns')
df1 =df1.drop('KitManufacturer',axis='columns')
df1 =df1.drop('OwnershipType',axis='columns')

In [113]:
df1.columns

Index(['AveragePlayerAge', 'TotalGoalsLastSeason', 'MatchesWonLastSeason',
       'MatchesDrawnLastSeason', 'MatchesLostLastSeason',
       'TotalGoalsConcededLastSeason', 'TotalRevenueLastSeason',
       'TransferIncomeLastSeason', 'NumberOfTrophies', 'MarketValueOfSquad',
       'AveragePlayerMarketValue', 'Country', 'PlayingStyle', 'Price'],
      dtype='object')

In [114]:
df1.isnull().sum()

AveragePlayerAge                0
TotalGoalsLastSeason            0
MatchesWonLastSeason            0
MatchesDrawnLastSeason          0
MatchesLostLastSeason           0
TotalGoalsConcededLastSeason    0
TotalRevenueLastSeason          0
TransferIncomeLastSeason        0
NumberOfTrophies                0
MarketValueOfSquad              0
AveragePlayerMarketValue        0
Country                         0
PlayingStyle                    0
Price                           0
dtype: int64

In [115]:
df1.AveragePlayerAge.unique()

array([24.36718202, 34.16214321, 30.44389701, ..., 30.73291644,
       26.8571855 , 32.64901408])

In [116]:
df1.TotalGoalsLastSeason.unique()

array([28, 89, 43, 84, 36, 56, 69, 64, 39, 78, 30, 74, 96, 77, 63, 33, 95,
       71, 53, 82, 46, 31, 57, 75, 59, 40, 51, 45, 55, 35, 97, 91, 58, 83,
       48, 50, 62, 38, 29, 79, 67, 20, 44, 87, 47, 21, 42, 81, 34, 23, 90,
       88, 80, 26, 76, 25, 60, 73, 41, 24, 70, 65, 22, 92, 86, 85, 66, 32,
       99, 49, 54, 68, 27, 94, 98, 61, 37, 72, 52, 93], dtype=int64)

In [117]:
df1.MatchesWonLastSeason.unique()

array([16, 12,  3, 19, 36, 14, 34, 22, 30, 27, 11, 24, 31,  4, 28, 35, 18,
       13,  2, 37, 29,  7, 23, 20,  8, 21, 26,  5, 17,  0, 15, 10, 32, 33,
        1,  9, 25,  6], dtype=int64)

In [118]:
df1.MatchesDrawnLastSeason.unique()

array([36, 35,  9, 19, 10, 37, 20, 30, 12, 17, 27,  5, 25,  3, 31,  1, 21,
       11,  2,  7, 28, 24,  8, 32, 13, 18,  6,  4, 16, 22, 14, 23, 29, 15,
        0, 33, 34, 26], dtype=int64)

In [119]:
df1.MatchesLostLastSeason.unique()

array([20, 31, 28, 34,  9, 33,  8, 18,  1,  2, 17, 26, 21, 13, 16, 24,  0,
       30, 22, 25, 27, 15, 23, 37, 32, 11, 10,  4,  5,  6, 19, 36,  7,  3,
       35, 14, 29, 12], dtype=int64)

In [120]:
df1 = df1.drop('TotalGoalsConcededLastSeason',axis='columns')

In [121]:
df1 = df1.drop('TotalRevenueLastSeason',axis='columns')

In [122]:
df1 = df1.drop('TransferIncomeLastSeason',axis='columns')

In [123]:
df1 = df1.drop('MatchesDrawnLastSeason',axis='columns')

In [124]:
df1 = df1.drop('MatchesLostLastSeason',axis='columns')

In [125]:
df1.columns

Index(['AveragePlayerAge', 'TotalGoalsLastSeason', 'MatchesWonLastSeason',
       'NumberOfTrophies', 'MarketValueOfSquad', 'AveragePlayerMarketValue',
       'Country', 'PlayingStyle', 'Price'],
      dtype='object')

In [126]:
df1.isnull().sum()

AveragePlayerAge            0
TotalGoalsLastSeason        0
MatchesWonLastSeason        0
NumberOfTrophies            0
MarketValueOfSquad          0
AveragePlayerMarketValue    0
Country                     0
PlayingStyle                0
Price                       0
dtype: int64

#### All the columns droped in the dataset have not much effects on the value of price

In [127]:
df1.head(5)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   
2         30.443897                    43                     3   
3         28.177194                    84                    19   
4         20.652317                    36                    36   

   NumberOfTrophies  MarketValueOfSquad  AveragePlayerMarketValue  Country  \
0                49          713.968872                 15.847841  England   
1                38          236.644694                 26.731697    Spain   
2                38          410.502058                 21.365171    Spain   
3                 6          177.561791                 21.483504    Italy   
4                11          562.114098                 26.938414   France   

     PlayingStyle          Price  
0  Counter-Attack     43,751,816  
1       Defensive    859,750,388  
2       Attacking  2,168,913,729  
3  Counter-Attack  1,426,481,894  
4  Counter-Attack  4,038,110,631

In [128]:
dummies2 = pd.get_dummies(df1['Country'])
dummies2.head(2)

England  France  Germany  Italy  Spain
0     True   False    False  False  False
1    False   False    False  False   True

In [129]:
dummies1 = pd.get_dummies(df1['PlayingStyle'])
dummies1.head(2)

Attacking  Counter-Attack  Defensive  Possession
0      False            True      False       False
1      False           False       True       False

In [130]:
df2 = pd.concat([df1,dummies2,dummies1],axis='columns')
df2.head(2)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   

   NumberOfTrophies  MarketValueOfSquad  AveragePlayerMarketValue  Country  \
0                49          713.968872                 15.847841  England   
1                38          236.644694                 26.731697    Spain   

     PlayingStyle        Price  England  France  Germany  Italy  Spain  \
0  Counter-Attack   43,751,816     True   False    False  False  False   
1       Defensive  859,750,388    False   False    False  False   True   

   Attacking  Counter-Attack  Defensive  Possession  
0      False            True      False       False  
1      False           False       True       False

In [131]:
df3 = df2.drop('Country',axis='columns')
df3.head(2)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   

   NumberOfTrophies  MarketValueOfSquad  AveragePlayerMarketValue  \
0                49          713.968872                 15.847841   
1                38          236.644694                 26.731697   

     PlayingStyle        Price  England  France  Germany  Italy  Spain  \
0  Counter-Attack   43,751,816     True   False    False  False  False   
1       Defensive  859,750,388    False   False    False  False   True   

   Attacking  Counter-Attack  Defensive  Possession  
0      False            True      False       False  
1      False           False       True       False

In [132]:
df3 = df3.drop('PlayingStyle',axis='columns')
df3.head(2)

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   

   NumberOfTrophies  MarketValueOfSquad  AveragePlayerMarketValue  \
0                49          713.968872                 15.847841   
1                38          236.644694                 26.731697   

         Price  England  France  Germany  Italy  Spain  Attacking  \
0   43,751,816     True   False    False  False  False      False   
1  859,750,388    False   False    False  False   True      False   

   Counter-Attack  Defensive  Possession  
0            True      False       False  
1           False       True       False

In [133]:
df3 = df3.drop(index=20435)

In [141]:
df3 = df3.drop(index=21767)

In [149]:
df3 = df3.drop(index=17472)

In [150]:
df3.head()

AveragePlayerAge  TotalGoalsLastSeason  MatchesWonLastSeason  \
0         24.367182                    28                    16   
1         34.162143                    89                    12   
2         30.443897                    43                     3   
3         28.177194                    84                    19   
4         20.652317                    36                    36   

   NumberOfTrophies  MarketValueOfSquad  AveragePlayerMarketValue  \
0                49          713.968872                 15.847841   
1                38          236.644694                 26.731697   
2                38          410.502058                 21.365171   
3                 6          177.561791                 21.483504   
4                11          562.114098                 26.938414   

           Price  England  France  Germany  Italy  Spain  Attacking  \
0     43,751,816     True   False    False  False  False      False   
1    859,750,388    False   False    False  False   True      False   
2  2,168,913,729    False   False    False  False   True       True   
3  1,426,481,894    False   False    False   True  False      False   
4  4,038,110,631    False    True    False  False  False      False   

   Counter-Attack  Defensive  Possession  
0            True      False       False  
1           False       True       False  
2           False      False       False  
3            True      False       False  
4            True      False       False

----------------------------------------------------------------------------------

------------------------------------------------------------------------------------

In [151]:
X = df3.drop('Price',axis='columns')

In [152]:
Y = df3.Price

In [153]:
df3.isnull().sum()

AveragePlayerAge            0
TotalGoalsLastSeason        0
MatchesWonLastSeason        0
NumberOfTrophies            0
MarketValueOfSquad          0
AveragePlayerMarketValue    0
Price                       0
England                     0
France                      0
Germany                     0
Italy                       0
Spain                       0
Attacking                   0
Counter-Attack              0
Defensive                   0
Possession                  0
dtype: int64

In [154]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=10)

In [155]:
df3.shape

(49997, 16)

In [156]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

ValueError: could not convert string to float: '3,415,844,033'