In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df = pd.read_csv('heart.csv')
df.head(2)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   

   caa  thall  output  
0    0      1       1  
1    0      2       1

#### Columns Dictionary:

Age : Age of the patient

Sex : Sex of the patient

exang: exercise induced angina (1 = yes; 0 = no)

ca: number of major vessels (0-3)

cp : Chest Pain type chest pain type

Value 1: typical angina
Value 2: atypical angina
Value 3: non-anginal pain
Value 4: asymptomatic
trtbps : resting blood pressure (in mm Hg)

chol : cholestoral in mg/dl fetched via BMI sensor

fbs : (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)

rest_ecg : resting electrocardiographic results

Value 0: normal
Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
thalach : maximum heart rate achieved

target : 0= less chance of heart attack 1= more chance of heart attack

In [40]:
df.shape

(303, 14)

In [41]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [42]:
df['sex'].unique()

array([1, 0], dtype=int64)

In [43]:
df['cp'].unique()  # values of cp are described in the column dictionary.

array([3, 2, 1, 0], dtype=int64)

In [44]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [45]:
df1 = df.drop(columns=['caa','oldpeak','slp','thall'])
df1.head(2)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  output
0   63    1   3     145   233    1        0       150     0       1
1   37    1   2     130   250    0        1       187     0       1

In [46]:
X = df1.drop(columns=['output'])
X.head(2)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng
0   63    1   3     145   233    1        0       150     0
1   37    1   2     130   250    0        1       187     0

In [47]:
Y = df1['output']
Y.head(2)

0    1
1    1
Name: output, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

In [49]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.7377049180327869

In [50]:
def predict_attack(age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng):
    
    x = np.zeros(len(X.columns))
    x[0] = age
    x[1] = sex
    x[2] = cp
    x[3] = trtbps
    x[4] = chol
    x[5] = fbs
    x[6] = restecg
    x[7] = thalachh
    x[8] = exng


    return model.predict([x])[0],

In [57]:
df1['exng'].unique()

array([0, 1], dtype=int64)

In [64]:
predict_attack(13,1,3,148,198,0,0,90,0)

c:\Users\akr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(1,)

In [65]:
predict_attack(70,1,3,215,289,0,1,90,1)

c:\Users\akr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(0,)

In [66]:
predict_attack(43,0,3,99,317,0,1,90,0)

c:\Users\akr\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(1,)